Controllers/CreatorsController.cs
using IBlogs.Data;
using IBlogs.Models.ViewModels;
using IBlogs.Repository;
using Microsoft.AspNetCore.Mvc;

namespace IBlogs.Controllers
{
    public class CreatorsController : Controller
    {
        private readonly IBlogDbContext blogDbContext;
        private readonly ICreatorsRepository creatorsRepository;

        public CreatorsController(IBlogDbContext blogDbContext, ICreatorsRepository creatorsRepository)
        {
            this.blogDbContext = blogDbContext;
            this.creatorsRepository = creatorsRepository;
        }
        public async Task<IActionResult> List()
        {
            var creators = blogDbContext.Profiles.ToList();
            List<ProfileRequest> listViewModel = new List<ProfileRequest>();

            foreach (var profile in creators)
            {
                var model = new ProfileRequest
                {
                    ProfileId = profile.ProfileId,
                    ProfileImage = profile.ProfileImage,
                    Name = profile.Name,
                    LastName = profile.LastName,
                    Email = profile.Email,
                    Gender = profile.Gender,
                    MyTopics = await creatorsRepository.UserTopics(profile.ProfileId)
                };
                listViewModel.Add(model);
            }

            return View(listViewModel);

            
        }
       
    }
}

Controllers/ForumController.cs
using Microsoft.AspNetCore.Mvc;

namespace IBlogs.Controllers
{
    public class ForumController : Controller
    {
        public IActionResult Room()
        {
            return View();
        }
    }
}

Controllers/ProfileController.cs
using IBlogs.Data;
using IBlogs.Models.Domain;
using IBlogs.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IBlogs.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IBlogDbContext blogDbContext;

        public ProfileController(IBlogDbContext blogDbContext)
        {
            this.blogDbContext = blogDbContext;
        }

        public IActionResult MyProfile(Guid id)
        {
            var categoryFromDb = blogDbContext.Profiles.FirstOrDefault(x => x.ProfileId == id);
            if (categoryFromDb != null)
            {
                var profileRequest = new ProfileRequest
                {
                    ProfileId = categoryFromDb.ProfileId,
                    Name = categoryFromDb.Name,
                    LastName = categoryFromDb.LastName,
                    ProfileImage = categoryFromDb.ProfileImage,
                    About = categoryFromDb.About,
                    Gender = categoryFromDb.Gender
                };
                return View(profileRequest);
            }
            return View();
        }
        public IActionResult List()
        {
            var users = blogDbContext.Profiles.ToList();

            return View(users);
        }

        public IActionResult Edit(Guid id)
        {
            var user = blogDbContext.Profiles.FirstOrDefault(x => x.ProfileId == id);
            if (user != null)
            {
                var edit = new EditRequest
                {
                    Name = user.Name,
                    LastName = user.LastName,
                    Email = user.Email,
                    Password = user.Password,
                    ConfirmPassword = user.ConfirmPassword,
                    About = user.About,
                    Gender = user.Gender
                };
                return View(edit);
            }
            return View(null);
        }
        [HttpPost]
        public IActionResult Edit(Guid id, EditRequest editRequest)
        {

            if (editRequest.Name == editRequest.LastName)
            {
                ModelState.AddModelError("name", "The Name and Last Name cannot be same");
            }

            if (editRequest.Password != editRequest.ConfirmPassword)
            {
                ModelState.AddModelError("", "Password and Confirmed password are not the same");
                return View();
            }


            if (ModelState.IsValid)
            {
                var editSend = new EditRequest
                {
                    ProfileId = id,
                    Name = editRequest.Name,
                    LastName = editRequest.LastName,
                    Email = editRequest.Email,
                    Password = editRequest.Password,
                    ConfirmPassword = editRequest.ConfirmPassword,
                    About = editRequest.About,
                    Gender = editRequest.Gender
                };
                var user = blogDbContext.Profiles.FirstOrDefault(x => x.ProfileId == id);
                
                user.Name = editSend.Name;
                user.LastName = editSend.LastName;
                user.Email = editSend.Email;
                user.Password = editSend.Password;
                user.ConfirmPassword = editSend.ConfirmPassword;
                user.About = editSend.About;
                user.Gender = editSend.Gender;

                blogDbContext.Profiles.Update(user);
                blogDbContext.SaveChanges();

                return RedirectToAction("MyProfile", new { id = user.ProfileId });
            }
            return View(editRequest);
        }
    }
}

Views/Shared/_Layout.cshtml
@using IBlogs.Models.Domain;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Profile> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IBlogs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IBlogs.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<body class="bg-black">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow bg-transparent" style="z-index:10;">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index"><img class="logo" src="~/Images/IBlogsLogoVector.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between px-3">
                    <ul class="navbar-nav text-light flex-grow-1 px-5">
                        <li class="nav-item me-3">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">About Us</a>
                        </li>
                        <li class="nav-item me-3">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Creators" asp-action="List">See All Creators</a>
                        </li>
                        
                    </ul>
                     @if (signInManager.IsSignedIn(User))
                        {
                            <a class="align-items-center me-5" asp-controller="Forum" asp-action="Room"><img src="~/Images/SocialThoughtVector.png" style="width:100px;" /></a>
                           <a class="btn me-3 bg-dark text-light"
                                asp-controller="Profile"
                                asp-action="MyProfile"
                                asp-route-id="@signInManager.UserManager.GetUserAsync(User).Result.ProfileId">
                           
                                Profile

                           </a>

                        }
                        else
                        {
                        <a class="align-items-center me-5" asp-area="Identity" asp-page="/Account/Login"><img src="~/Images/SocialThoughtVector.png" style="width:100px;" /></a>
                            <a class="btn me-3 bg-dark text-light"
                               asp-area="Identity"
                               asp-page="/Account/Login">
                               Register
                          

                            </a>
                        }
                </div>
            </div>
        </nav>
       
    </header>
    
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>