Controllers/CreatorsController.cs
using IBlogs.Data;
using IBlogs.Models.ViewModels;
using IBlogs.Repository;
using Microsoft.AspNetCore.Mvc;

namespace IBlogs.Controllers
{
    public class CreatorsController : Controller
    {
        private readonly IBlogDbContext blogDbContext;
        private readonly ICreatorsRepository creatorsRepository;

        public CreatorsController(IBlogDbContext blogDbContext, ICreatorsRepository creatorsRepository)
        {
            this.blogDbContext = blogDbContext;
            this.creatorsRepository = creatorsRepository;
        }
        public async Task<IActionResult> List()
        {
            var creators = blogDbContext.Profiles.ToList();
            List<ProfileRequest> listViewModel = new List<ProfileRequest>();

            foreach (var profile in creators)
            {
                var model = new ProfileRequest
                {
                    ProfileId = profile.ProfileId,
                    ProfileImage = profile.ProfileImage,
                    Name = profile.Name,
                    LastName = profile.LastName,
                    Email = profile.Email,
                    Gender = profile.Gender,
                    MyTopics = await creatorsRepository.UserTopics(profile.ProfileId)
                };
                listViewModel.Add(model);
            }

            return View(listViewModel);

            
        }
       
    }
}

Controllers/ImageController.cs
using IBlogs.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IBlogs.Controllers
{
    public class ImageController : Controller
    {
        private readonly IBlogDbContext blogDbContext;

        public ImageController(IBlogDbContext blogDbContext)
        {
            this.blogDbContext = blogDbContext;
        }
        [HttpGet("{id}/image")]
        public IActionResult GetImage(Guid id)
        {

            var userProfile = blogDbContext.BlogPosts.FirstOrDefault(x => x.PostId == id);
            if (userProfile == null || userProfile.Image == null)
            {
                return NotFound();
            }
            var imageData = Convert.FromBase64String(userProfile.Image);
            return File(imageData, "image/jpeg");

        }
    }
}

Controllers/ProfileController.cs
using IBlogs.Data;
using IBlogs.Models.Domain;
using IBlogs.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IBlogs.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IBlogDbContext blogDbContext;

        public ProfileController(IBlogDbContext blogDbContext)
        {
            this.blogDbContext = blogDbContext;
        }

        public IActionResult MyProfile(Guid id)
        {
            var categoryFromDb = blogDbContext.Profiles.FirstOrDefault(x => x.ProfileId == id);
            if (categoryFromDb != null)
            {
                var profileRequest = new ProfileRequest
                {
                    ProfileId = categoryFromDb.ProfileId,
                    Name = categoryFromDb.Name,
                    LastName = categoryFromDb.LastName,
                    ProfileImage = categoryFromDb.ProfileImage,
                    About = categoryFromDb.About,
                    Gender = categoryFromDb.Gender
                };
                return View(profileRequest);
            }
            return View();
        }
        public IActionResult List()
        {
            var users = blogDbContext.Profiles.ToList();

            return View(users);
        }

        public IActionResult Edit(Guid id)
        {
            var user = blogDbContext.Profiles.FirstOrDefault(x => x.ProfileId == id);
            if (user != null)
            {
                var edit = new EditRequest
                {
                    Name = user.Name,
                    LastName = user.LastName,
                    Email = user.Email,
                    Password = user.Password,
                    ConfirmPassword = user.ConfirmPassword,
                    About = user.About,
                    Gender = user.Gender
                };
                return View(edit);
            }
            return View(null);
        }
        [HttpPost]
        public IActionResult Edit(Guid id, EditRequest editRequest)
        {

            if (editRequest.Name == editRequest.LastName)
            {
                ModelState.AddModelError("name", "The Name and Last Name cannot be same");
            }

            if (editRequest.Password != editRequest.ConfirmPassword)
            {
                ModelState.AddModelError("", "Password and Confirmed password are not the same");
                return View();
            }


            if (ModelState.IsValid)
            {
                var editSend = new EditRequest
                {
                    ProfileId = id,
                    Name = editRequest.Name,
                    LastName = editRequest.LastName,
                    Email = editRequest.Email,
                    Password = editRequest.Password,
                    ConfirmPassword = editRequest.ConfirmPassword,
                    About = editRequest.About,
                    Gender = editRequest.Gender
                };
                var user = blogDbContext.Profiles.FirstOrDefault(x => x.ProfileId == id);
                
                user.Name = editSend.Name;
                user.LastName = editSend.LastName;
                user.Email = editSend.Email;
                user.Password = editSend.Password;
                user.ConfirmPassword = editSend.ConfirmPassword;
                user.About = editSend.About;
                user.Gender = editSend.Gender;

                blogDbContext.Profiles.Update(user);
                blogDbContext.SaveChanges();

                return RedirectToAction("MyProfile", new { id = user.ProfileId });
            }
            return View(editRequest);
        }
    }
}

Views/Creators/List.cshtml
@model List<IBlogs.Models.ViewModels.ProfileRequest>
@using IBlogs.Models.Domain;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Profile> signInManager
@inject UserManager<Profile> userManager
<div class="container mt-3 mb-5">
    <div class="row">

        @if (Model != null && Model.Any())
        {
            @foreach (var obj in Model)
            {
                <div class="col-6 col-md-4 col-lg-3 mb-3 mx-3 px-3">
                    <div>
                        @if (obj.ProfileImage != null)
                        {
                            <img src="@Url.Action("GetImage", "Image", new { id = obj.ProfileId })" class="list-img">
                        }
                        else
                        {
                            if (obj.Gender == "Male")
                            {
                                <img src="~/Images/male_user.png" style="float:left;" class="list-img">
                            }
                            if (obj.Gender == "Female")
                            {
                                <img src="~/Images/female_user.png" style="float:left;" class="list-img">
                            }
                            if (obj.Gender == "Other" || obj.Gender == "Gender")
                            {
                                <img src="~/Images/Other.png" style="float:left;" class="list-img">
                            }

                        }
                    </div>
                    <div class="text-light">
                        <h3>@obj.Name @obj.LastName</h3>
                        <p>I like to speak about:</p>
                        @if (obj.MyTopics != null && obj.MyTopics.Count > 0)
                        {
                            @foreach (var topic in obj.MyTopics)
                            {
                                if (topic.Contains(","))
                                {
                                    var individualTopics = topic.Split(',');
                                    foreach (var individualTopic in individualTopics)
                                    {
                                        <span class="badge badge-sm bg-secondary m-1">@individualTopic.Trim()</span>
                                    }
                                }
                                else
                                {
                                    <span class="badge badge-sm bg-secondary m-1">@topic</span>
                                }
                            }
                        }
                        else
                        {
                            <span class="badge badge-sm bg-secondary bg-danger m-1">No specific topics</span>
                        }
                        <h4 class="mt-3">Contact me via mail: </h4>
                        <h5>@obj.Email</h5>
                        @if (signInManager.IsSignedIn(User))
                        {
                            <a class="btn btn-secondary"
                               asp-controller="Profile"
                               asp-action="MyProfile"
                               asp-route-id="@obj.ProfileId">
                                Check my profile
                            </a>
                        }
                        else
                        {
                            <a class="btn btn-secondary"
                                asp-area="Identity"
                                asp-page="/Account/Login">
                                Check my profile
                            </a>
                        }
                    </div>
                </div>
            }
        }


    </div>
</div>